/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "apiforward_constants.h"

namespace apiforward {

const apiforwardConstants g_apiforward_constants;

apiforwardConstants::apiforwardConstants() {
}

} // namespace

