/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef apiforward_CONSTANTS_H
#define apiforward_CONSTANTS_H

#include "apiforward_types.h"

namespace apiforward {

class apiforwardConstants {
 public:
  apiforwardConstants();

};

extern const apiforwardConstants g_apiforward_constants;

} // namespace

#endif
