/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "userdefined_constants.h"

namespace userdefined {

const userdefinedConstants g_userdefined_constants;

userdefinedConstants::userdefinedConstants() {
}

} // namespace

