/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef userdefined_CONSTANTS_H
#define userdefined_CONSTANTS_H

#include "userdefined_types.h"

namespace userdefined {

class userdefinedConstants {
 public:
  userdefinedConstants();

};

extern const userdefinedConstants g_userdefined_constants;

} // namespace

#endif
